INSERT INTO country_list (country_id,country_code,country_name) VALUES (1,'US','United States') ON CONFLICT DO NOTHING;

INSERT INTO country_list (country_id,country_code,country_name) VALUES (2,'CA','Canada') ON CONFLICT DO NOTHING;

INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('1','AB','Alberta','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('2','BC','British Columbia','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('3','MB','Manitoba','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('4','NB','New Brunswick','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('5','NL','Newfoundland and Labrador','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('6','NS','Nova Scotia','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('7','NT','Northwest Territories','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('8','NU','Nunavut','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('9','ON','Ontario','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('10','PE','Prince Edward Island','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('11','QC','Quebec','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('12','SK','Saskatchewan','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('13','YT','Yukon','2') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('14','AL','Alabama','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('15','AK','Alaska','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('16','AZ','Arizona','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('17','AR','Arkansas','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('18','CA','California','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('19','CO','Colorado','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('20','CT','Connecticut','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('21','DE','Delaware','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('22','FL','Florida','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('23','GA','Georgia','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('24','HI','Hawaii','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('25','ID','Idaho','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('26','IL','Illinois','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('27','IN','Indiana','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('28','IA','Iowa','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('29','KS','Kansas','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('30','KY','Kentucky','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('31','LA','Louisiana','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('32','ME','Maine','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('33','MD','Maryland','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('34','MA','Massachusetts','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('35','MI','Michigan','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('36','MN','Minnesota','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('37','MS','Mississippi','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('38','MO','Missouri','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('39','MT','Montana','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('40','NE','Nebraska','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('41','NV','Nevada','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('42','NH','New Hampshire','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('43','NJ','New Jersey','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('44','NM','New Mexico','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('45','NY','New York','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('46','NC','North Carolina','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('47','ND','North Dakota','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('48','OH','Ohio','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('49','OK','Oklahoma','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('50','OR','Oregon','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('51','PA','Pennsylvania','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('52','RI','Rhode Island','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('53','SC','South Carolina','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('54','SD','South Dakota','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('55','TN','Tennessee','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('56','TX','Texas','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('57','UT','Utah','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('58','VT','Vermont','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('59','VI','Virgin Islands','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('60','VA','Virginia','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('61','WA','Washington','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('62','WV','West Virginia','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('63','WI','Wisconsin','1') ON CONFLICT DO NOTHING;
INSERT INTO state_list(state_id,state_code,state_name,country_id) VALUES ('64','WY','Wyoming','1') ON CONFLICT DO NOTHING;

